# # Use an official Node.js runtime as the base image
# FROM node:14-alpine

# # Set the working directory inside the container
# WORKDIR /app

# # Copy the package.json and package-lock.json files
# COPY package*.json ./

# # Install the project dependencies
# RUN npm install

# # Copy the rest of the project files
# COPY . .

# # Expose the port that the React app runs on (default is 3000 for create-react-app)
# EXPOSE 3000

# # Command to run the React app
# CMD ["npm", "run", "dev"]
